#!/bin/sh

if [ $# -ne 1 ]; then
    echo >&2 "Usage: ${0##*/} RECIPE"
    exit 0
elif [ "$1" = "--complete" ]; then
    exit 0
fi

echo "You can also use: oe-pkgdata-util list-pkg-files -p RECIPE"
echo
oe-pkgdata-util list-pkg-files -p "$1"
