#!/usr/bin/env python3
# Usage: bb edit [-h] [-p] [-r] target [target ...]
# Summary: Edit bitbake recipes, included files, and bbappends
# Help: See bb edit -h for detailed usage information.

import logging
import os
import pipes
import sys
import bbcmd
import bb
import bb.cache
import bb.codeparser
import bb.utils


logger = logging.getLogger('bb.edit')


def prompt(filenames, editor='vi'):
    """Show a basic menu to select a file to edit"""
    while True:
        for number, filename in enumerate(filenames):
            print('{0}) {1}'.format(number, filename))
        print('q) quit')

        try:
            orig_answer = raw_input('File to edit? ')
        except EOFError:
            return

        if not orig_answer:
            continue
        answer = orig_answer.upper()

        if answer in ('Q', 'X', 'QUIT', 'EXIT'):
            print("Exiting")
            break

        try:
            number = int(answer)
        except ValueError:
            print("Invalid input '{0}'".format(answer))
            continue

        run_editor([filenames[number]], editor)


def run_editor(files, editor='vi'):
    """Run the user's editor of choice editing the specified files"""
    logger.info("Editing these files:\n%s", ''.join(f + '\n' for f in files))
    os.system(editor + ' ' + ' '.join(pipes.quote(arg) for arg in files))


def targets_to_files(tinfoil, targets, with_includes=True):
    """Return the filenames corresponding to the requested targets.

    This includes bbappends, and can optionally also include included files
    (e.g. .inc files).
    """
    files = []
    for target in targets:
        filename = tinfoil.build_target_to_fn(target)
        recipe_data = tinfoil.parse_metadata(target)

        files.append(filename)

        if with_includes:
            cfg_included = tinfoil.localdata.getVar('BBINCLUDED', True).split()
            recipe_included = recipe_data.getVar('BBINCLUDED', True).split()
            final_included = [f for f in (set(recipe_included) - set(cfg_included)) if not f.endswith('.bbclass')]
            final_included.sort(key=lambda k: k.endswith('.bbappend'))

            files.extend(final_included)
        else:
            appends = tinfoil.cooker.collection.get_file_appends(filename)
            files.extend(appends)
    return list(bbcmd.iter_uniq(bb.cache.Cache.virtualfn2realfn(f)[0] for f in files))


def edit(args):
    # tinfoil sets up log output for the bitbake loggers, but bb uses
    # a separate namespace at this time
    bbcmd.setup_log_handler(logging.getLogger('bb'))

    editor = args.editor or os.getenv('VISUAL', os.getenv('EDITOR', 'vi'))

    tinfoil = bbcmd.Tinfoil(output=sys.stderr)
    tinfoil.prepare()
    tinfoil.prepare_taskdata(args.targets)

    files_to_edit = targets_to_files(tinfoil, args.targets,
                                     with_includes=not args.just_recipes)
    if files_to_edit is None:
        return 1

    if args.prompt:
        prompt(files_to_edit, editor)
    else:
        run_editor(files_to_edit, editor)


# provide bb completions
def main(arguments):
    parser = bbcmd.CompleteParser()
    parser.add_argument('-e', '--editor',
                        help='specify the editor to run (default: $VISUAL or $EDITOR or vi)')
    parser.add_argument('-p', '--prompt', action='store_true',
                        help='rather than opening all the files at once, prompt the user')
    parser.add_argument('-r', '--just-recipes', action='store_true',
                        help='only edit recipes and appends, not included files')
    parser.add_argument('targets', nargs='+', help='targets to edit')

    args = parser.parse_args(arguments)
    if args is None:
        # showing completions
        return
    else:
        return edit(args)


if __name__ == '__main__':
    bbcmd.run_main(main)
