#!/bin/sh

usage () {
    cat >&2 <<END
Usage: bb generated RECIPE

List the names of the packages that the specified recipe generated.
END
    exit 1
}

while getopts h opt; do
    case "$opt" in
        h|\?)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    echo >&2 "Error: incorrect number of arguments"
    usage
fi

if [ "$1" = "--complete" ]; then
    exit 0
fi

oe-pkgdata-util list-pkgs --runtime --recipe "$1"
