#!/bin/bash
# Usage: bb latest recipe

set -euo pipefail

import argparse
import sys
from pathlib import Path

import bb.tinfoil

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='bb-latest')
    parser.add_argument('recipe', help='recipe name')
    args = parser.parse_args()

    with bb.tinfoil.Tinfoil() as tinfoil:
        tinfoil.prepare()

        corelib = Path(tinfoil.config_data.getVar('COREBASE')) / 'meta' / 'lib'
        sys.path.insert(0, str(corelib))

        import oe.recipeutils

        data = tinfoil.parse_recipe(args.recipe)
        # TODO handle UPSTREAM_VERSION_UNKNOWN and UPSTREAM_CHECK_UNRELIABLE
        uv = oe.recipeutils.get_recipe_upstream_version(data)
        print(uv)
