#!/usr/bin/env python3
# Usage: bb latest recipe

import sys
from pathlib import Path

import bb.tinfoil

import bbcmd


def latest(args):
    with bb.tinfoil.Tinfoil() as tinfoil:
        tinfoil.prepare()

        corelib = Path(tinfoil.config_data.getVar('COREBASE')) / 'meta' / 'lib'
        sys.path.insert(0, str(corelib))

        import oe.recipeutils

        data = tinfoil.parse_recipe(args.recipe)
        # TODO handle UPSTREAM_VERSION_UNKNOWN and UPSTREAM_CHECK_UNRELIABLE
        uv = oe.recipeutils.get_recipe_upstream_version(data)
        print(uv)


# provide bb completions
def main(arguments):
    parser = bbcmd.CompleteParser()
    parser.add_argument('recipe', help='recipe name')

    args = parser.parse_args(arguments)
    if args is None:
        # showing completions
        return
    else:
        return latest(args)


if __name__ == '__main__':
    bbcmd.run_main(main)
