#!/bin/sh
# Usage: bb shell
# Summary: Enter an interactive mode shell (repl)
# Help: This shell requires repl (https://github.com/defunkt/repl) to function,
# and rlwrap is recommended to gain basic shell completion and other readline
# features (http://utopia.knoware.nl/~hlub/uck/rlwrap/).

repl=$(type -p repl 2>/dev/null)
if [ $? -ne 0 ]; then
    echo >&2 "Error: 'repl' must be installed to run the bb shell"
    exit 1
fi

rlwrap=$(type -p rlwrap 2>/dev/null)
if [ $? -ne 0 ]; then
    echo >&2 "Warning: the bb shell is less functional without 'rlwrap' installed"
fi

mkdir -p ~/.repl
bb commands >~/.repl/bb

repl bb
